#ifndef CALCELEMENT_GLOBAL_H
#define CALCELEMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCELEMENT_LIBRARY)
#  define CALCELEMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALCELEMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCELEMENT_GLOBAL_H
